### ISSUE TITLE
would like to know how to install this....any step by step instructions?

### ISSUE THREAD

**Issue by dduran1210** [CountMurphy/QTalarm#10]
tried the qmake, make...etc  and nothing works.

tried the .configure...that sucks too.

no easy way to do this?  without having to earn a programmer's degree in tech?

**Comment by CountMurphy** [comment]
Well there is building, and then there is installing. Building should be fairly straight forward. I'm going to assume you are running some kind of linux distro. If you are running Arch linux, you can install it directly from the AUR (https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages) and it will do all these steps for you. If not Arch, no worries. I'll walk you through it

# Building
1. You need QT5 installed on your system first. 
1. cd into the directory with the QTAlarm source files.
1. In the termnal, type  "qmake" This will create a "Makefile"
1. type "make"  When done, a new file called "qtalarm" should have been created. This is application itself. You can test it by typing "./qtalarm" in your terminal. The application should run. There will not be any entries for it start menu (or whatever that is called in your desktop environment at this point).

# Installing
1. copy qtalarm into /usr/bin  (`sudo cp qtalarm /usr/bin`). 
1. inside of the source code directory, there is a directory called "Icons."  These icons need to be copied with the following commands:
    - `sudo cp 1349069370_Alarm_Clock.png /usr/share/icons/hicolor/48x48/apps/`
    - `sudo cp Icons/1349069370_Alarm_Clock24.png /usr/share/icons/hicolor/24x24/apps/1349069370_Alarm_Clock.png`
    - `sudo cp 1349069370_Alarm_Clock16.png /usr/share/icons/hicolor/16x16/apps/1349069370_Alarm_Clock.png`
1. Last step. We need to create a "Desktop Entry" file to include QTalarm in your systems list of programs. Save the following text into a file called `qtalarm.desktop` located here `/usr/share/applications/qtalarm.desktop`
```
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=QTalarm
GenericName=QTalarm
Comment= A nifty alarm clock written in QT
Icon=1349069370_Alarm_Clock.png
Exec=qtalarm
Categories=Application;Utility;
```

That should be it. Let me know if this works for you or if anything mentioned above wasn't clear. I'll add these instructions to the wiki once I've confirmed you got it installed.

**Comment by dduran1210** [comment]
thank you . I  was VERY frustrated with the hassles in Xubuntu 20 although
I really liked the distro.

But i gave up and uninstalled it and moved to MX-LINUX...instead.

I saved your email instructions for when the NEXT Xubuntu comes out version
21 or whatever, then will probably give that
one a shot.   Hopefully, they will have this alarm included without the
hassles

Dave
