### ISSUE TITLE
Opening a second instance shouldn't be possible

### ISSUE THREAD

**Issue by Kommynct** [CountMurphy/QTalarm#17]
The proper behavior, since it has a tray icon, would be for opening another instance not to duplicate the process, but to bring the window to the front.

**Comment by CountMurphy** [comment]
Plan to address in coming release.

**Comment by Kommynct** [comment]
the patch notes seem to state this is resolved but after installing qtalarm again from the aur I've noticed no change.

**Comment by CountMurphy** [comment]
The last release patched https://github.com/CountMurphy/QTalarm/issues/19 (as it was a really quick fix). I have yet to write a fix for this one. I was hoping QT had a native way to enforce a single instance, but couldn't find one. I plan on coding up something to address this next.

**Comment by CountMurphy** [comment]
fixed in d8e04068e288110e9be823460c56fd2256f3caef. Sorry this took so long. QT has no native way to list running processes. Had to create a local socket and communicate over that
