### ISSUE TITLE
New build fails to run on Debian

### ISSUE THREAD

**Issue by Tafnab** [CountMurphy/QTalarm#19]
I was rebuilding this for Debian 11 (MX 21).  The build was successful, but the program will not open a window, and hangs immediately.  Kernel 5.18.0, Qt 5.15.2.  Can't see any log files, so sorry can't offer any insight.

**Comment by CountMurphy** [comment]
Out of town at the moment, but I'll fire up a VM when I get back and investigate sometime next week

**Comment by CountMurphy** [comment]
@Tafnab, what Desktop Environment are you using?

**Comment by CountMurphy** [comment]
Just built it in Debian 11. Seems to work fine in gnome:

![running](https://i.imgur.com/3ilWSmX.png)

**Comment by Tafnab** [comment]
Xfce 4.16
CPU: 6-Core 12th Gen Intel Core i5-12600 (-MT MCP-) speed/min/max: 600/800/6100 MHz 
Kernel: 5.18.0-4mx-amd64 x86_64

**Comment by CountMurphy** [comment]
I *think* I see whats happening. Once you run the program, do you see an orange alarm clock icon in your taskbar?
![xfce](https://i.imgur.com/NFUlO8m.png) 

If so, all you got to do is click it and the window will show. I have a preferences area in the app that can set if the window shows on load. When it starts for the first time that setting blank. Looks like under gnome the window just shows. XFCE, it doesn't. I'll tweak the code for the next release to have a default setting (show window). Can you confirm that's what happening on your end?

**Comment by Tafnab** [comment]
That's got it.  Thanks.

**Comment by CountMurphy** [comment]
Default show window behavior implemented in latest version
