### ISSUE TITLE
Alarm takes 15-30 seconds after given time

### ISSUE THREAD

**Issue by Xeno-Idaltu** [CountMurphy/QTalarm#20]
I built the app on Kubuntu-22 and it is extremely buggy when it comes to setting the alarm.

Sometimes it functions right away but most of the time it takes 15-30 seconds after said time. Sometimes it never sounds the alarm.

I was planning on using it as my daily alarm but it's not reliable at this moment.

I really don't want to install K-Alarm because it installs bloatware I never use. Please fix it and submit to the KDE Project as a standalone alternative for K-Alarm

**Comment by CountMurphy** [comment]
Can't replicate the issue on Kubuntu-22. Do you have any terminal output from the app? Is anything else on the system running slowly?

**Comment by Xeno-Idaltu** [comment]
Nothing shows up when ran on the terminal. Is it necessary to install it as Root?
I have installed on /home/$USER/.local/bin/qtalarm

I also changed widget styles. Breeze, Oxygen, QT-Curve..they all have the same delay.

**Comment by Xeno-Idaltu** [comment]
Is there a folder I need to delete. Before building it I used the appimage, I'm  not if there is any conflict as I can't see folders titled "qtalarm"

**Comment by CountMurphy** [comment]
QTalarm does not need root for anything. It shouldn't matter where the binary itself lives (.local/bin is fine). The only directory that it  needs is $HOME/.config/qtalarm. Not sure what is causing the delay for you. The app itself checks the time twice a second looking for any matches to the alarms. To double check I just set up a few more alarms in kubuntu 22 and they all went off when they should have.

What are the specs for your system?

**Comment by Xeno-Idaltu** [comment]
I installed a QT based alarm called Zeit and it functions without any problems.

It's a 2011 gaming laptop but I don't think its the computer..
