### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by zvezdochiot** [CountMurphy/QTalarm#21]
Hi @CountMurphy .

Correct `LICENSE` file. See https://github.com/X11-good-tools/qtalarm

**Comment by CountMurphy** [comment]
Other than minor formatting, these files are exactly the same.

**Comment by zvezdochiot** [comment]
@CountMurphy say:
>these files are exactly the same.

Only your file is not recognized by github. Your repo is labeled as a repo with an unknown license.

**Comment by CountMurphy** [comment]
That is a fair point. I'll get that updated later this week.

**Comment by CountMurphy** [comment]
updated

**Comment by zvezdochiot** [comment]
Hi @CountMurphy .

The commit https://github.com/CountMurphy/QTalarm/commit/bb7002e88ad2c1654246fc0bc8f6cf5da73da0d4 has the description "reformated GPL license file ". 
It should have been called "fix #21: converted GPL license file". 
Then the issue would be closed automatically and a link to it would be saved in git-history. As in "Merge pull request".

**Comment by CountMurphy** [comment]
Yes, I'm aware how github works, thanks.
