### ISSUE TITLE
Crash after completeing math

### ISSUE THREAD

**Issue by PQCraft** [CountMurphy/QTalarm#26]
Entering a correct answer on an alarm set to ask a math question causes a `Segmentation fault (core dumped)`

**Comment by CountMurphy** [comment]
I'm able to replicate this only on my laptop when pressing enter after inputting the correct answer. Clicking ok does not trigger the crash. However, on my development machine I cannot trigger the crash at all. 

Could you post the contents of your config file? Assuming linux its under `~/.config/QTalarm/QTalarm.conf`. Also are you also hitting enter or clicking ok on the math prompt?

**Comment by PQCraft** [comment]
I am hitting enter
Here is my `QTalarm.conf`: [QTalarm.conf.txt](https://github.com/CountMurphy/QTalarm/files/12790277/QTalarm.conf.txt)

**Comment by CountMurphy** [comment]
I think I have it fixed in commit 52a9a6fe51ad6aa026adc0d586f0bda86459cb75. Please let me know if the crash continues

**Comment by PQCraft** [comment]
yep no more crash
thanks :+1:
