### ISSUE TITLE
QTalarm doesn't loads, or Window is not visible

### ISSUE THREAD

**Issue by SurajKhayamali** [CountMurphy/QTalarm#6]
The program is running, But no window can be seen.

**Comment by CountMurphy** [comment]
Not seeing the issue running KDE/plasma. What OS are you running? If linux, what desktop environment? I'll try to replicate your setup on my end to see whats wrong,

**Comment by CountMurphy** [comment]
By default, the main window is hidden unless you access the program from its system tray icon. If you dont see an icon, there is one thing we can try. If (running linux) edit the file .config/QTalarm/QTalarm.conf and add this line near the end:

    ShowWindowDefault=true

**Comment by SurajKhayamali** [comment]
I am using windows,
Yeah, It's working; was in system tray where i didn't looked earlier.
Thanks a lot!
