### ISSUE TITLE
Please provide a LICENSE file

### ISSUE THREAD

**Issue by mnhauke** [CountMurphy/QTalarm#7]
I've been trying to work out what license QTalarm is under. 
The Licensing section of README.md states that the project is licensed under "GPLv3".

But I can't see a LICENSE file in the repository.

All the source and header files contains no license information at all.

I suspect that QTalarm is completely licensed under the GPL-3.0-only (not later) license, but I think this needs to be made completely clear.

Thanks.

**Comment by CountMurphy** [comment]
added with commit 47ac0fe242376b80a032a00c8744b175186f0a86

**Comment by CountMurphy** [comment]
fixed with commit a4aad0a02069f607e724c48bc5334b5f0749ab18
