### ISSUE TITLE
No sound for qtalarm

### ISSUE THREAD

**Issue by lsh2000ou** [CountMurphy/QTalarm#8]
Hi there,

Following your instructions, I compiled the files and was able to ran qtalarm. However, when I tested it. There was no sound. When the preset time reaches, there was a pop-up window but without sound. Any idea?

Thanks.

Jeff

**Comment by CountMurphy** [comment]
What operating system are you running it on? Is QT5-multimedia installed? If you run the app from the terminal is anything printed?

**Comment by lsh2000ou** [comment]
Thanks. I solved the issue by sudo apt-get install libqt5multimedia5-plugins

**Comment by CountMurphy** [comment]
Glad its working!
