### ISSUE TITLE
User interface problem: things don't quite fit

### ISSUE THREAD

**Issue by dubhater** [CountMurphy/QTalarm#9]
Hi!

I just tried QTalarm and noticed some problems:

![qtalarm1](https://user-images.githubusercontent.com/1739488/94038383-06102380-fdcf-11ea-8b60-91326bf629ca.png)
![qtalarm2](https://user-images.githubusercontent.com/1739488/94038379-05778d00-fdcf-11ea-8741-7cfc5f79c89d.png)

Are you setting some sizes manually instead of letting the widgets/layouts decide how big they need to be?

Also, clicking on the system tray icon brings up QTalarm's window, but clicking again doesn't make it go away.

This is in Arch Linux, with Plasma.

**Comment by CountMurphy** [comment]
The icon click will be easy to fix for sure. The widget label size issue is one is something I've known about but never gotten around to fixing. I'll try to have both patched this weekend.

**Comment by CountMurphy** [comment]
@dubhater, I think I found the problem. What font size are you using in Plasma? The system default is at 10. The reason I never fixed this issue before was I could never replicate it on any of my systems. The font size in your screen shots looked a bit large, so I changed my system font size and now I can replicate what you are seeing. 

So far I can fix the labels by enabling word-wrap, but the check boxes don't seem to have that option. Before dedicating more time to the fix I'd like to confirm that your system font size is over 10 pt.

**Comment by dubhater** [comment]
Yes, the system font size is 12, and I have "Force font DPI: 120" as well.

**Comment by CountMurphy** [comment]
Should be fixed with commit ca76a5e02a2357fe15c811703d446ceb041fd649. AUR has been updated. Feel free to reopen if there are other UI issues.

**Comment by dubhater** [comment]
It's much better now. Thanks!
